spring.application.name=tinder-ai-backend
spring.ai.ollama.chat.options.model=llama3.2:3b
tinderai.character.user = {id: 'user', firstName: 'Suffian', lastName: 'Akhtar', age: 30, ethnicity: 'Pakistani', gender: 'MALE', bio: 'Software Engineer, I like reading and making things', imageUrl: '', myBriggsPersonalityType: 'INTP'}